for portainer add-on
ubuntu/microk8s pull request #1650
Opened 2020-10-15 11:42 UTC by balasu

2020-10-15 12:04 UTC, ktsakalozos commented on tests/test-addons.py
> +        print("Disabling Portainer")
I think you are missing the disable command here.

2020-10-15 12:05 UTC, ktsakalozos requested changes
Thank you for this PR @balasu . You will also need to add your addon at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/addon-lists.yaml

2020-10-17 01:26 UTC, balchua reviewed
We may want to keep `$ARCH` here `cdkbot/microbot-amd64`, i think the team ran the tests on multiple arch too.

2020-11-16 15:26 UTC, ktsakalozos approved these changes
LGTM +1 thanky ou for the PR @balasu

2020-11-16 15:27 UTC, merged